# Test sops.age.generateKey, which upstream sops-nix only implements as a NixOS
# activation script. system-manager runs that script from the
# sops-generate-age-key.service oneshot instead.
#
# The secrets themselves are decrypted with an SSH host key, so that the test
# can assert both that the age key gets generated and that secret installation
# still succeeds afterwards.
{
  forEachDistro,
  sops-nix,
  ...
}:

let
  keyFile = "/var/lib/sops-nix/key.txt";
in

forEachDistro "sops-generate-age-key" {
  modules = [
    (
      { ... }:
      {
        imports = [ sops-nix.nixosModules.sops ];

        config.sops = {
          age = {
            generateKey = true;
            inherit keyFile;
            sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
          };
          defaultSopsFile = ../sops/secrets-ssh.yaml;
          secrets.test = { };
        };
      }
    )
  ];
  extraPathsToRegister = [ ../sops/ssh-ed25519-key ];
  testScriptFunction =
    { ... }:
    ''
      start_all()

      machine.wait_for_unit("multi-user.target")

      # Provide the SSH host key that sops uses as an age identity.
      machine.succeed("mkdir -p /etc/ssh")
      machine.succeed("cp ${../sops/ssh-ed25519-key} /etc/ssh/ssh_host_ed25519_key")
      machine.succeed("chmod 600 /etc/ssh/ssh_host_ed25519_key")

      machine.fail("test -e ${keyFile}")

      machine.activate()

      # The age key is generated by a unit, not silently dropped.
      machine.succeed("systemctl is-active sops-generate-age-key.service")
      machine.succeed("test -f ${keyFile}")

      key_mode = machine.succeed("stat -c %a ${keyFile}").strip()
      assert key_mode == "600", f"Expected age key mode 600, got {key_mode}"

      key = machine.succeed("cat ${keyFile}")
      assert "AGE-SECRET-KEY-" in key, f"Expected an age key in ${keyFile}, got: {key}"

      # Secret installation still runs, and runs after the key generation.
      machine.succeed("systemctl is-active sops-install-secrets.service")
      secret_value = machine.succeed("cat /run/secrets/test").strip()
      assert secret_value == "itworks-ssh", f"Expected 'itworks-ssh', got '{secret_value}'"

      before = machine.succeed("systemctl show -p Before --value sops-generate-age-key.service")
      assert "sops-install-secrets.service" in before, f"Expected ordering before sops-install-secrets.service, got: {before}"

      # Re-activating must not replace an already generated key.
      key_before = machine.succeed("cat ${keyFile}")
      machine.activate()
      key_after = machine.succeed("cat ${keyFile}")
      assert key_before == key_after, "Re-activation regenerated the age key"
    '';
}
