pub mod etc_tree;
use anyhow::Context;
use im::HashMap;
use regex;
use serde::{Deserialize, Serialize};
use std::collections::HashSet;
use std::fs::Permissions;
use std::os::unix::prelude::PermissionsExt;
use std::os::unix::{self, fs as unixfs};
use std::path::{Path, PathBuf};
use std::sync::OnceLock;
use std::{fs, io};

use super::ActivationResult;
use crate::activate::{ActivationError, EtcFilesState};
use crate::{etc_dir, remove_file, remove_link, StorePath};

type EtcActivationResult = ActivationResult<EtcFilesState>;
/// The state we managed to build, plus every target we failed to write.
///
/// Only the success path carries the failure list: an error here means the walk
/// was abandoned, so there is no per-file outcome to report.
type EtcActivationOutcome = Result<(EtcFilesState, Vec<PathBuf>), ActivationError<EtcFilesState>>;

static UID_GID_REGEX: OnceLock<regex::Regex> = OnceLock::new();

fn get_uid_gid_regex() -> &'static regex::Regex {
    UID_GID_REGEX.get_or_init(|| regex::Regex::new(r"^\+[0-9]+$").expect("could not compile regex"))
}

const BACKUP_SUFFIX: &str = "system-manager-backup";

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct EtcFile {
    source: StorePath,
    target: PathBuf,
    uid: u32,
    gid: u32,
    group: String,
    user: String,
    mode: String,
    #[serde(default)]
    replace_existing: bool,
}

type EtcFiles = HashMap<String, EtcFile>;

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct EtcFilesConfig {
    entries: EtcFiles,
    static_env: StorePath,
}

impl std::fmt::Display for EtcFilesConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let out: String = itertools::intersperse(
            self.entries.iter().map(|entry| {
                format!(
                    "target: {}, source:{}, mode:{}",
                    entry.1.target.display(),
                    entry.1.source,
                    entry.1.mode
                )
            }),
            "\n".to_owned(),
        )
        .collect();
        write!(f, "{out}")
    }
}

fn read_config(store_path: &StorePath) -> anyhow::Result<EtcFilesConfig> {
    log::info!("Reading etc file definitions...");
    let file = fs::File::open(
        Path::new(&store_path.store_path)
            .join("etcFiles")
            .join("etcFiles.json"),
    )?;
    let reader = io::BufReader::new(file);
    let config: EtcFilesConfig = serde_json::from_reader(reader)?;
    log::debug!("{config}");
    Ok(config)
}

/// Etc files activation
///
/// The activation is performed in two main steps:
///
/// 1. We list all the entries living in the nix-generated static env. These files
///    are generated by some Nix derivation, there is no way for them to appear in the
///    eval-time generated configuration.
/// 2. After merging the "static" entries listed in the previous step with the "copy" ones
///    coming from the system-manager state, we create all these files on the disk, backing
///    up the conflicts if necessary.
pub fn activate(
    store_path: &StorePath,
    old_state: EtcFilesState,
    ephemeral: bool,
) -> EtcActivationOutcome {
    let config = read_config(store_path)
        .map_err(|e| ActivationError::with_partial_result(old_state.clone(), e))?;

    let etc_dir = etc_dir(ephemeral);
    log::info!("Creating /etc entries in {}", etc_dir.display());

    // Walk through static link, list entries
    let mut entries = match list_static_entries(&config) {
        Ok(e) => e,
        Err(e) => {
            return Err(ActivationError::WithPartialResult {
                result: old_state,
                source: e,
            })
        }
    };
    let mut non_static_entries: Vec<EtcFile> = config
        .entries
        .values()
        .filter(|v| v.mode != "symlink")
        .cloned()
        .map(|mut v| {
            v.source.store_path = v.source.store_path.join(&v.target);
            v
        })
        .collect();
    entries.append(&mut non_static_entries);
    // Create dirs and link/copy entries
    let (mut new_state, failed) =
        create_etc_files(entries, EtcFilesState::default(), &old_state, &etc_dir);
    retain_failed_targets(&mut new_state, &old_state, &failed);
    // Delete unecessary files
    let files_to_delete: HashSet<PathBuf> = old_state
        .files
        .difference(&new_state.files)
        .map(|f| f.to_owned())
        .collect();
    new_state = delete_paths(&files_to_delete, new_state);
    Ok((new_state, failed))
}

/// Carry a target we failed to write over from the old state.
///
/// Without this it looks like a target that left the configuration: we would
/// delete the file we just failed to replace, and forget that it was ever ours,
/// so the next activation would refuse to touch it as unmanaged.
fn retain_failed_targets(state: &mut EtcFilesState, old_state: &EtcFilesState, failed: &[PathBuf]) {
    for target in failed {
        if old_state.backed_up_files.contains(target) {
            state.backed_up_files.insert(target.clone());
        } else if old_state.files.contains(target) {
            state.files.insert(target.clone());
        }
    }
}

pub fn deactivate(old_state: EtcFilesState) -> EtcActivationResult {
    let files = old_state.files.clone();
    let mut final_state = delete_paths(&files, old_state);
    for file_to_restore in &final_state.backed_up_files.clone() {
        let _ = restore_backup(file_to_restore)
            .map(|_| final_state.backed_up_files.remove(&file_to_restore.clone()));
    }
    log::info!("Done");
    Ok(final_state)
}

fn backup_path_for(path: &Path) -> PathBuf {
    let mut s = path.to_owned();
    s.add_extension(BACKUP_SUFFIX);
    s
}

/// Clear a directory sitting where a managed file belongs.
///
/// Such a path can neither be unlinked (EISDIR) nor moved into the backup slot,
/// because rename(2) refuses to put a directory back over the symlink we create
/// (ENOTDIR), which would leave the backup unrestorable. An empty directory has
/// nothing worth keeping, so drop it; anything else needs an operator, and
/// recursing under /etc on the strength of a state file is not a trade worth
/// making.
fn remove_dir_in_the_way(target: &Path) -> anyhow::Result<()> {
    log::info!(
        "Trying to remove empty directory in the way: {}",
        target.display()
    );
    fs::remove_dir(target).with_context(|| {
        format!(
            "{} is a non-empty directory where a file is expected, remove it and re-run",
            target.display()
        )
    })
}

fn backup_existing_file(path: &Path) -> anyhow::Result<()> {
    let backup_path = backup_path_for(path);
    // fs::rename clobbers its destination, which would discard the
    // pre-system-manager original that deactivate restores from.
    if backup_path.exists() || backup_path.is_symlink() {
        anyhow::bail!(
            "Refusing to overwrite the existing backup at {}",
            backup_path.display()
        );
    }
    log::info!(
        "Backing up existing file {} to {}",
        path.display(),
        backup_path.display()
    );
    fs::rename(path, &backup_path)?;
    Ok(())
}

fn restore_backup(path: &Path) -> anyhow::Result<()> {
    let backup_path = backup_path_for(path);
    if backup_path.exists() || backup_path.is_symlink() {
        log::info!(
            "Restoring backup {} to {}",
            backup_path.display(),
            path.display()
        );
        fs::rename(&backup_path, path)?;
    } else {
        log::warn!(
            "Backup file {} not found, cannot restore",
            backup_path.display()
        );
    }
    Ok(())
}

fn delete_paths(paths: &HashSet<PathBuf>, mut state: EtcFilesState) -> EtcFilesState {
    for path in paths {
        if path.exists() {
            if path.is_symlink() {
                let _ = remove_link(path).map(|_| state.files.remove(path));
            } else if path.is_file() {
                let _ = remove_file(path).map(|_| state.files.remove(path));
            } else {
                log::warn!(
                    "Trying to delete {}, but it seems to be a directory",
                    path.display()
                );
            }
        }
        if state.backed_up_files.contains(path) {
            let _ = restore_backup(path).map(|_| state.backed_up_files.remove(path));
        }
    }
    state
}

/// List all the files contained in `config_entries` in a DFS fashion.
fn list_static_entries(config_entries: &EtcFilesConfig) -> anyhow::Result<Vec<EtcFile>> {
    let mut files = Vec::new();

    /// Helper data structure used to keep track of the relative path
    /// from the `static_env` directory.
    #[derive(Clone)]
    struct DirToVisit {
        absolute_path: PathBuf,
        path_from_root: PathBuf,
    }

    let mut dirs_to_visit: Vec<DirToVisit> = vec![DirToVisit {
        absolute_path: config_entries.static_env.store_path.clone(),
        path_from_root: PathBuf::from(""),
    }];
    let mut i = 0;

    while i < dirs_to_visit.len() {
        let dir = dirs_to_visit
            .get(i)
            .context("ERROR: index error in dir loop")?
            .clone();
        let dir_content = fs::read_dir(&dir.absolute_path)?;
        for file in dir_content {
            let file = file?;
            let canon_path = fs::canonicalize(file.path()).context(format!(
                "Failed to get the canonical path of {}",
                file.path().display()
            ))?;
            if canon_path.is_dir() {
                log::debug!("{} is a dir", canon_path.display());
                let dirname = file.file_name();
                let mut path_from_root = dir.path_from_root.clone();
                path_from_root.push(dirname);
                dirs_to_visit.push(DirToVisit {
                    absolute_path: canon_path,
                    path_from_root,
                });
            } else {
                log::debug!("{} is a file", file.path().display());
                let target = dir.path_from_root.clone().join(file.file_name());
                // Is this file entry available in the config? If so, inherit replace_existing.
                let replace_existing = config_entries
                    .entries
                    .iter()
                    .find(|e| e.1.target == target)
                    .map(|e| e.1.replace_existing)
                    .unwrap_or(false);
                let etc_file = EtcFile {
                    source: StorePath {
                        store_path: canon_path,
                    },
                    target: PathBuf::from("/etc").join(target),
                    uid: 0,
                    gid: 0,
                    group: "".to_string(),
                    user: "".to_string(),
                    mode: "symlink".to_string(),
                    replace_existing,
                };
                log::debug!(
                    "add file: {:?}, path_from_root: {:?}, absolute_path: {:?}",
                    etc_file,
                    dir.path_from_root,
                    dir.absolute_path
                );
                files.push(etc_file);
            }
        }
        i += 1;
    }
    Ok(files)
}

fn create_etc_files(
    mut files: Vec<EtcFile>,
    mut state: EtcFilesState,
    old_state: &EtcFilesState,
    etc_dir: &Path,
) -> (EtcFilesState, Vec<PathBuf>) {
    let mut failed = Vec::new();
    files.sort_by(|a, b| a.target.cmp(&b.target));
    for file in files {
        let target = PathBuf::from(etc_dir).join(&file.target);
        state = match create_etc_file(file, state, old_state, etc_dir) {
            Ok(state) => state,
            Err(ActivationError::WithPartialResult { result, source }) => {
                log::warn!("Can't link/copy {}: {}", target.display(), source);
                failed.push(target);
                result
            }
        }
    }
    (state, failed)
}

/// Create a single etc file.
///
/// We separated this from `create_etc_files` to catch any error on a file
/// boundary, so that failing to link one file does not abandon the rest of the
/// walk. The caller still collects those failures and fails the activation.
fn create_etc_file(
    file: EtcFile,
    mut state: EtcFilesState,
    old_state: &EtcFilesState,
    etc_dir: &Path,
) -> EtcActivationResult {
    let target = PathBuf::from(etc_dir).join(&file.target);
    log::debug!(
        "Creating {} to {} ({})",
        file.source,
        target.display(),
        file.target.display()
    );
    // Create all dirs
    log::debug!("Creating all dirs up to {:?}", target.parent());
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent).map_err(|e| {
            ActivationError::with_partial_result(
                state.clone(),
                anyhow::Error::from(e)
                    .context(format!("creating the parent dir of {}", target.display())),
            )
        })?;
    }

    // We want to override all the Ubuntu systemd .wants and .requires entries.
    // We did not find a proper way to do that from the Nix static env,
    // hardcoding this condition in the activation instead.
    let target_is_in_systemd_dir = is_inside_systemd_dependency_dir(&target);

    if file.mode == "symlink" {
        // On some symlinks, target.exists() returns false. Not sure why.
        let mut exists = target.exists() || target.is_symlink();
        let may_replace =
            old_state.contains(&target) || file.replace_existing || target_is_in_systemd_dir;
        if exists && may_replace && !target.is_symlink() && target.is_dir() {
            remove_dir_in_the_way(&target)
                .map_err(|e| ActivationError::with_partial_result(state.clone(), e))?;
            exists = false;
        }
        if exists {
            // If the target exists and has been created by a previous system-manager activation,
            // replace it.
            if old_state.contains(&target) {
                log::debug!(
                    "{} is managed by system-manager. Deleting.",
                    target.display()
                );
                fs::remove_file(&target).map_err(|e| ActivationError::WithPartialResult {
                    result: state.clone(),
                    source: e.into(),
                })?;
                log::debug!("{} is managed by system-manager.", target.display());
                unix::fs::symlink(file.source.store_path, &target).map_err(|e| {
                    ActivationError::WithPartialResult {
                        result: state.clone(),
                        source: e.into(),
                    }
                })?;
                // Check whether this file is a backup or plain link in the old state.
                if old_state.files.contains(&target) {
                    state.files.insert(target);
                } else {
                    state.backed_up_files.insert(target);
                }
            } else if file.replace_existing || target_is_in_systemd_dir {
                log::debug!(
                    "{} already exists but it's set to replace. Backup and link again.",
                    file.source
                );
                state = backup_and_link(&target, &file.source.store_path, state)?;
            } else {
                log::warn!(
                    "Error while creating file in /etc: Unmanaged path already exists in filesystem, please remove it and run system-manager again: {}\nSet replaceExisting if you're willing to override it.",
                    target.display()
                );
            }
        } else {
            // Target do not exist on the filesystem
            log::debug!("Symlink {} => {}", file.source, target.display());
            unix::fs::symlink(file.source.store_path, &target).map_err(|e| {
                ActivationError::WithPartialResult {
                    result: state.clone(),
                    source: e.into(),
                }
            })?;
            // A target we backed up once keeps that classification even if our
            // symlink has since gone missing, so that deactivate still has the
            // original to restore.
            if old_state.backed_up_files.contains(&target) {
                state.backed_up_files.insert(target);
            } else {
                state.files.insert(target);
            }
        }
    } else {
        log::debug!("{} is a regular file", file.source);
        state = copy_file(&file.source.store_path, &target, &file, old_state, state)?;
    }
    Ok(state)
}

fn backup_and_link(
    target: &Path,
    link_path: &Path,
    mut dir_state: EtcFilesState,
) -> EtcActivationResult {
    backup_existing_file(target)
        .map_err(|e| ActivationError::with_partial_result(dir_state.clone(), e))?;
    log::debug!("Symlink {} => {}", link_path.display(), target.display());
    unix::fs::symlink(link_path, target).map_err(|e| ActivationError::WithPartialResult {
        result: dir_state.clone(),
        source: e.into(),
    })?;
    dir_state.backed_up_files.insert(target.to_owned());
    Ok(dir_state)
}

/// Check whether link_path is inside a systemd .wants or .requires directory.
fn is_inside_systemd_dependency_dir(link_path: &Path) -> bool {
    link_path
        .parent()
        .map(|parent| {
            parent
                .extension()
                .filter(|ext| ["wants", "requires"].iter().any(|other| other == ext))
                .is_some()
                && parent
                    .parent()
                    .map(|pp| pp.ends_with("systemd/system"))
                    .unwrap_or(false)
        })
        .unwrap_or(false)
}

fn find_uid(entry: &EtcFile) -> anyhow::Result<u32> {
    if !get_uid_gid_regex().is_match(&entry.user) {
        nix::unistd::User::from_name(&entry.user)
            .map(|maybe_user| {
                maybe_user.map_or_else(
                    || {
                        log::warn!(
                            "Specified user {} not found, defaulting to root",
                            entry.user
                        );
                        0
                    },
                    |user| user.uid.as_raw(),
                )
            })
            .map_err(|err| anyhow::anyhow!(err).context("Failed to determine user"))
    } else {
        Ok(entry.uid)
    }
}

fn find_gid(entry: &EtcFile) -> anyhow::Result<u32> {
    if !get_uid_gid_regex().is_match(&entry.group) {
        nix::unistd::Group::from_name(&entry.group)
            .map(|maybe_group| {
                maybe_group.map_or_else(
                    || {
                        log::warn!(
                            "Specified group {} not found, defaulting to root",
                            entry.group
                        );
                        0
                    },
                    |group| group.gid.as_raw(),
                )
            })
            .map_err(|err| anyhow::anyhow!(err).context("Failed to determine group"))
    } else {
        Ok(entry.gid)
    }
}

/// Copy a file from source to target.
/// Failing to copy a file doesn't abandon the rest of the walk, hence the
/// per-file error return; the caller collects it and fails the activation.
fn copy_file(
    source: &Path,
    target: &PathBuf,
    entry: &EtcFile,
    old_state: &EtcFilesState,
    mut new_state: EtcFilesState,
) -> EtcActivationResult {
    let mut exists = target.exists() || target.is_symlink();
    if exists
        && (old_state.contains(target) || entry.replace_existing)
        && !target.is_symlink()
        && target.is_dir()
    {
        remove_dir_in_the_way(target).map_err(|e| to_activation_result(e, &new_state))?;
        exists = false;
    }
    let exists_and_need_backup = exists && !old_state.contains(target) && entry.replace_existing;
    if exists && !old_state.contains(target) {
        if exists_and_need_backup {
            backup_existing_file(target).map_err(|e| ActivationError::WithPartialResult {
                result: new_state.clone(),
                source: e,
            })?;
        } else {
            // Deliberately left alone rather than clobbered, so this is not a
            // failure and must not fail the activation.
            log::warn!("File {} already exists, ignoring. Set replaceExisting if you want to back it up and override it.", target.display());
            return Ok(new_state);
        }
    };
    log::debug!(
        "Copying file {} to {}...",
        source.display(),
        target.display()
    );
    fn to_activation_result<E: Into<anyhow::Error>>(
        e: E,
        state: &EtcFilesState,
    ) -> ActivationError<EtcFilesState> {
        ActivationError::WithPartialResult {
            result: state.clone(),
            source: e.into(),
        }
    }
    if exists && old_state.contains(target) {
        log::debug!("remove {}, we're managing it.", target.display());
        fs::remove_file(target).map_err(|e| to_activation_result(e, &new_state))?;
    }
    log::debug!("copy {} to {}", source.display(), target.display());
    fs::copy(source, target).map_err(|e| to_activation_result(e, &new_state))?;
    let mode_int =
        u32::from_str_radix(&entry.mode, 8).map_err(|e| to_activation_result(e, &new_state))?;
    fs::set_permissions(target, Permissions::from_mode(mode_int))
        .map_err(|e| to_activation_result(e, &new_state))?;
    unixfs::chown(
        target,
        Some(find_uid(entry).map_err(|e| to_activation_result(e, &new_state))?),
        Some(find_gid(entry).map_err(|e| to_activation_result(e, &new_state))?),
    )
    .map_err(|e| to_activation_result(e, &new_state))?;
    // Update the state depending whether or not we backed up a file before
    if exists_and_need_backup || (old_state.backed_up_files.contains(target)) {
        new_state.backed_up_files.insert(target.clone());
    } else {
        new_state.files.insert(target.clone());
    }
    Ok(new_state)
}

#[cfg(test)]
mod tests {
    use super::*;

    struct Fixture {
        _tmp: tempfile::TempDir,
        etc: PathBuf,
        source: PathBuf,
    }

    fn fixture() -> Fixture {
        let tmp = tempfile::tempdir().expect("tempdir");
        let etc = tmp.path().join("etc");
        let store = tmp.path().join("store");
        fs::create_dir_all(&etc).unwrap();
        fs::create_dir_all(&store).unwrap();
        let source = store.join("managed.conf");
        fs::write(&source, "managed\n").unwrap();
        Fixture {
            _tmp: tmp,
            etc,
            source,
        }
    }

    fn entry(target: &str, source: &Path, mode: &str, replace_existing: bool) -> EtcFile {
        EtcFile {
            source: StorePath {
                store_path: source.to_owned(),
            },
            target: PathBuf::from(target),
            uid: 0,
            gid: 0,
            group: "+0".to_owned(),
            user: "+0".to_owned(),
            mode: mode.to_owned(),
            replace_existing,
        }
    }

    #[test]
    fn an_empty_directory_at_the_target_is_replaced() {
        let f = fixture();
        fs::create_dir_all(f.etc.join("nix/nix.conf")).unwrap();

        let (state, failed) = create_etc_files(
            vec![entry("nix/nix.conf", &f.source, "symlink", true)],
            EtcFilesState::default(),
            &EtcFilesState::default(),
            &f.etc,
        );

        assert!(failed.is_empty(), "unexpected failures: {failed:?}");
        let target = f.etc.join("nix/nix.conf");
        assert!(target.is_symlink(), "target should be our symlink");
        assert_eq!(fs::read_to_string(&target).unwrap(), "managed\n");
        assert!(state.files.contains(&target));
    }

    #[test]
    fn a_non_empty_directory_at_the_target_fails_and_is_left_alone() {
        let f = fixture();
        fs::create_dir_all(f.etc.join("nix/nix.conf")).unwrap();
        fs::write(f.etc.join("nix/nix.conf/keep"), "keep me\n").unwrap();

        let (state, failed) = create_etc_files(
            vec![entry("nix/nix.conf", &f.source, "symlink", true)],
            EtcFilesState::default(),
            &EtcFilesState::default(),
            &f.etc,
        );

        assert_eq!(failed, vec![f.etc.join("nix/nix.conf")]);
        assert!(
            f.etc.join("nix/nix.conf/keep").exists(),
            "a non-empty directory must never be deleted"
        );
        assert!(state.files.is_empty());
    }

    #[test]
    fn a_managed_directory_at_the_target_is_replaced() {
        let f = fixture();
        let target = f.etc.join("nix/nix.conf");
        fs::create_dir_all(&target).unwrap();
        let old_state = EtcFilesState {
            files: HashSet::from([target.clone()]),
            ..EtcFilesState::default()
        };

        let (_, failed) = create_etc_files(
            vec![entry("nix/nix.conf", &f.source, "symlink", false)],
            EtcFilesState::default(),
            &old_state,
            &f.etc,
        );

        assert!(failed.is_empty(), "unexpected failures: {failed:?}");
        assert!(target.is_symlink());
    }

    #[test]
    fn an_unmanaged_symlink_target_without_replace_existing_is_skipped_without_failing() {
        let f = fixture();
        let target = f.etc.join("keep-me");
        fs::write(&target, "original\n").unwrap();

        let (state, failed) = create_etc_files(
            vec![entry("keep-me", &f.source, "symlink", false)],
            EtcFilesState::default(),
            &EtcFilesState::default(),
            &f.etc,
        );

        assert!(failed.is_empty(), "a deliberate skip is not a failure");
        assert_eq!(fs::read_to_string(&target).unwrap(), "original\n");
        assert!(state.files.is_empty());
    }

    #[test]
    fn an_unmanaged_copy_target_without_replace_existing_is_skipped_without_failing() {
        let f = fixture();
        let target = f.etc.join("keep-me");
        fs::write(&target, "original\n").unwrap();

        let (state, failed) = create_etc_files(
            vec![entry("keep-me", &f.source, "0644", false)],
            EtcFilesState::default(),
            &EtcFilesState::default(),
            &f.etc,
        );

        assert!(failed.is_empty(), "a deliberate skip is not a failure");
        assert_eq!(fs::read_to_string(&target).unwrap(), "original\n");
        assert!(state.files.is_empty());
    }

    #[test]
    fn a_failed_target_stays_managed_and_is_not_deleted() {
        let f = fixture();
        let target = f.etc.join("nix/nix.conf");
        fs::create_dir_all(&target).unwrap();
        fs::write(target.join("keep"), "keep me\n").unwrap();
        let old_state = EtcFilesState {
            files: HashSet::from([target.clone()]),
            ..EtcFilesState::default()
        };

        let (mut state, failed) = create_etc_files(
            vec![entry("nix/nix.conf", &f.source, "symlink", false)],
            EtcFilesState::default(),
            &old_state,
            &f.etc,
        );
        assert_eq!(failed, vec![target.clone()]);
        retain_failed_targets(&mut state, &old_state, &failed);

        assert!(state.files.contains(&target), "must stay managed");
        assert!(
            old_state.files.difference(&state.files).next().is_none(),
            "must not be scheduled for deletion"
        );
    }

    #[test]
    fn a_failed_target_keeps_its_backup_classification() {
        let f = fixture();
        let target = f.etc.join("sudoers");
        let old_state = EtcFilesState {
            backed_up_files: HashSet::from([target.clone()]),
            ..EtcFilesState::default()
        };
        let mut state = EtcFilesState::default();

        retain_failed_targets(&mut state, &old_state, std::slice::from_ref(&target));

        assert!(state.backed_up_files.contains(&target));
        assert!(state.files.is_empty());
    }

    #[test]
    fn an_existing_backup_is_never_overwritten() {
        let f = fixture();
        let target = f.etc.join("sudoers");
        fs::write(&target, "current\n").unwrap();
        fs::write(backup_path_for(&target), "installer original\n").unwrap();

        let (_, failed) = create_etc_files(
            vec![entry("sudoers", &f.source, "symlink", true)],
            EtcFilesState::default(),
            &EtcFilesState::default(),
            &f.etc,
        );

        assert_eq!(failed, vec![f.etc.join("sudoers")]);
        assert_eq!(
            fs::read_to_string(backup_path_for(&target)).unwrap(),
            "installer original\n"
        );
    }
}
