pub mod etc_tree;
use anyhow::{anyhow, Context};
use im::HashMap;
use regex;
use serde::{Deserialize, Serialize};
use std::collections::HashSet;
use std::fs::Permissions;
use std::os::unix::prelude::PermissionsExt;
use std::os::unix::{self, fs as unixfs};
use std::path::{Path, PathBuf};
use std::sync::OnceLock;
use std::{fs, io};

use super::ActivationResult;
use crate::activate::{ActivationError, EtcFilesState};
use crate::{etc_dir, remove_file, remove_link, StorePath};

type EtcActivationResult = ActivationResult<EtcFilesState>;

static UID_GID_REGEX: OnceLock<regex::Regex> = OnceLock::new();

fn get_uid_gid_regex() -> &'static regex::Regex {
    UID_GID_REGEX.get_or_init(|| regex::Regex::new(r"^\+[0-9]+$").expect("could not compile regex"))
}

const BACKUP_SUFFIX: &str = "system-manager-backup";

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct EtcFile {
    source: StorePath,
    target: PathBuf,
    uid: u32,
    gid: u32,
    group: String,
    user: String,
    mode: String,
    #[serde(default)]
    replace_existing: bool,
}

type EtcFiles = HashMap<String, EtcFile>;

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct EtcFilesConfig {
    entries: EtcFiles,
    static_env: StorePath,
}

impl std::fmt::Display for EtcFilesConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let out: String = itertools::intersperse(
            self.entries.iter().map(|entry| {
                format!(
                    "target: {}, source:{}, mode:{}",
                    entry.1.target.display(),
                    entry.1.source,
                    entry.1.mode
                )
            }),
            "\n".to_owned(),
        )
        .collect();
        write!(f, "{out}")
    }
}

fn read_config(store_path: &StorePath) -> anyhow::Result<EtcFilesConfig> {
    log::info!("Reading etc file definitions...");
    let file = fs::File::open(
        Path::new(&store_path.store_path)
            .join("etcFiles")
            .join("etcFiles.json"),
    )?;
    let reader = io::BufReader::new(file);
    let config: EtcFilesConfig = serde_json::from_reader(reader)?;
    log::debug!("{config}");
    Ok(config)
}

/// Etc files activation
///
/// The activation is performed in two main steps:
///
/// 1. We list all the entries living in the nix-generated static env. These files
///    are generated by some Nix derivation, there is no way for them to appear in the
///    eval-time generated configuration.
/// 2. After merging the "static" entries listed in the previous step with the "copy" ones
///    coming from the system-manager state, we create all these files on the disk, backing
///    up the conflicts if necessary.
pub fn activate(
    store_path: &StorePath,
    old_state: EtcFilesState,
    ephemeral: bool,
) -> EtcActivationResult {
    let config = read_config(store_path)
        .map_err(|e| ActivationError::with_partial_result(old_state.clone(), e))?;

    let etc_dir = etc_dir(ephemeral);
    log::info!("Creating /etc entries in {}", etc_dir.display());

    let mut new_state = EtcFilesState::default();

    // Walk through static link, list entries
    let mut entries = match list_static_entries(&config) {
        Ok(e) => e,
        Err(e) => {
            return Err(ActivationError::WithPartialResult {
                result: new_state.clone(),
                source: e,
            })
        }
    };
    let mut non_static_entries: Vec<EtcFile> = config
        .entries
        .values()
        .filter(|v| v.mode != "symlink")
        .cloned()
        .map(|mut v| {
            v.source.store_path = v.source.store_path.join(&v.target);
            v
        })
        .collect();
    entries.append(&mut non_static_entries);
    // Create dirs and link/copy entries
    let mut errors = Vec::new();
    new_state = create_etc_files(
        entries,
        new_state.clone(),
        &old_state,
        &etc_dir,
        &mut errors,
    );
    // Delete unecessary files
    let files_to_delete: HashSet<PathBuf> = old_state
        .files
        .difference(&new_state.files)
        .map(|f| f.to_owned())
        .collect();
    new_state = delete_paths(&files_to_delete, new_state);
    if errors.is_empty() {
        Ok(new_state)
    } else {
        let messages: Vec<String> = errors.iter().map(|e| format!("{e:#}")).collect();
        Err(ActivationError::with_partial_result(
            new_state,
            anyhow::anyhow!(
                "{} etc file error(s):\n{}",
                messages.len(),
                messages.join("\n")
            ),
        ))
    }
}

pub fn deactivate(old_state: EtcFilesState) -> EtcActivationResult {
    let files = old_state.files.clone();
    let mut final_state = delete_paths(&files, old_state);
    for file_to_restore in &final_state.backed_up_files.clone() {
        let _ = restore_backup(file_to_restore)
            .map(|_| final_state.backed_up_files.remove(&file_to_restore.clone()));
    }
    log::info!("Done");
    Ok(final_state)
}

fn backup_path_for(path: &Path) -> PathBuf {
    let mut s = path.to_owned();
    s.add_extension(BACKUP_SUFFIX);
    s
}

fn backup_existing_file(path: &Path) -> anyhow::Result<()> {
    let backup_path = backup_path_for(path);
    log::info!(
        "Backing up existing file {} to {}",
        path.display(),
        backup_path.display()
    );
    fs::rename(path, &backup_path)?;
    Ok(())
}

fn restore_backup(path: &Path) -> anyhow::Result<()> {
    let backup_path = backup_path_for(path);
    if backup_path.exists() || backup_path.is_symlink() {
        log::info!(
            "Restoring backup {} to {}",
            backup_path.display(),
            path.display()
        );
        fs::rename(&backup_path, path)?;
    } else {
        log::warn!(
            "Backup file {} not found, cannot restore",
            backup_path.display()
        );
    }
    Ok(())
}

fn delete_paths(paths: &HashSet<PathBuf>, mut state: EtcFilesState) -> EtcFilesState {
    for path in paths {
        if path.exists() {
            if path.is_symlink() {
                let _ = remove_link(path).map(|_| state.files.remove(path));
            } else if path.is_file() {
                let _ = remove_file(path).map(|_| state.files.remove(path));
            } else {
                log::warn!(
                    "Trying to delete {}, but it seems to be a directory",
                    path.display()
                );
            }
        }
        if state.backed_up_files.contains(path) {
            let _ = restore_backup(path).map(|_| state.backed_up_files.remove(path));
        }
    }
    state
}

/// List all the files contained in `config_entries` in a DFS fashion.
fn list_static_entries(config_entries: &EtcFilesConfig) -> anyhow::Result<Vec<EtcFile>> {
    let mut files = Vec::new();

    /// Helper data structure used to keep track of the relative path
    /// from the `static_env` directory.
    #[derive(Clone)]
    struct DirToVisit {
        absolute_path: PathBuf,
        path_from_root: PathBuf,
    }

    let mut dirs_to_visit: Vec<DirToVisit> = vec![DirToVisit {
        absolute_path: config_entries.static_env.store_path.clone(),
        path_from_root: PathBuf::from(""),
    }];
    let mut i = 0;

    while i < dirs_to_visit.len() {
        let dir = dirs_to_visit
            .get(i)
            .context("ERROR: index error in dir loop")?
            .clone();
        let dir_content = fs::read_dir(&dir.absolute_path)?;
        for file in dir_content {
            let file = file?;
            let canon_path = fs::canonicalize(file.path()).context(format!(
                "Failed to get the canonical path of {}",
                file.path().display()
            ))?;
            if canon_path.is_dir() {
                log::debug!("{} is a dir", canon_path.display());
                let dirname = file.file_name();
                let mut path_from_root = dir.path_from_root.clone();
                path_from_root.push(dirname);
                dirs_to_visit.push(DirToVisit {
                    absolute_path: canon_path,
                    path_from_root,
                });
            } else {
                log::debug!("{} is a file", file.path().display());
                let target = dir.path_from_root.clone().join(file.file_name());
                // Is this file entry available in the config? If so, inherit replace_existing.
                let replace_existing = config_entries
                    .entries
                    .iter()
                    .find(|e| e.1.target == target)
                    .map(|e| e.1.replace_existing)
                    .unwrap_or(false);
                let etc_file = EtcFile {
                    source: StorePath {
                        store_path: canon_path,
                    },
                    target: PathBuf::from("/etc").join(target),
                    uid: 0,
                    gid: 0,
                    group: "".to_string(),
                    user: "".to_string(),
                    mode: "symlink".to_string(),
                    replace_existing,
                };
                log::debug!(
                    "add file: {:?}, path_from_root: {:?}, absolute_path: {:?}",
                    etc_file,
                    dir.path_from_root,
                    dir.absolute_path
                );
                files.push(etc_file);
            }
        }
        i += 1;
    }
    Ok(files)
}

fn create_etc_files(
    mut files: Vec<EtcFile>,
    mut state: EtcFilesState,
    old_state: &EtcFilesState,
    etc_dir: &Path,
    errors: &mut Vec<anyhow::Error>,
) -> EtcFilesState {
    files.sort_by(|a, b| a.target.cmp(&b.target));
    for file in files {
        let target = file.target.clone();
        state = match create_etc_file(file, state, old_state, etc_dir) {
            Ok(state) => state,
            Err(ActivationError::WithPartialResult { result, source }) => {
                log::error!(
                    "Error while creating file in {}: {source:?}",
                    target.display()
                );
                errors.push(source);
                result
            }
        }
    }
    state
}

/// Create a single etc file.
///
/// We separated this from `create_etc_files` to catch any error on a file boundary
/// to make sure failing to link a file do not cancel the whole etc activation.
fn create_etc_file(
    file: EtcFile,
    mut state: EtcFilesState,
    old_state: &EtcFilesState,
    etc_dir: &Path,
) -> EtcActivationResult {
    let target = PathBuf::from(etc_dir).join(&file.target);
    log::debug!(
        "Creating {} to {} ({})",
        file.source,
        target.display(),
        file.target.display()
    );
    // Create all dirs
    log::debug!("Creating all dirs up to {:?}", target.parent());
    target.parent().map(fs::create_dir_all);

    // We want to override all the Ubuntu systemd .wants and .requires entries.
    // We did not find a proper way to do that from the Nix static env,
    // hardcoding this condition in the activation instead.
    let target_is_in_systemd_dir = is_inside_systemd_dependency_dir(&target);

    if file.mode == "symlink" {
        // On some symlinks, target.exists() returns false. Not sure why.
        let exists = target.exists() || target.is_symlink();
        if exists {
            // If the target exists and has been created by a previous system-manager activation,
            // replace it.
            if old_state.contains(&target) {
                log::debug!(
                    "{} is managed by system-manager. Deleting.",
                    &target.display()
                );
                fs::remove_file(&target).map_err(|e| ActivationError::WithPartialResult {
                    result: state.clone(),
                    source: e.into(),
                })?;
                log::debug!("{} is managed by system-manager.", &target.display());
                unix::fs::symlink(file.source.store_path, &target).map_err(|e| {
                    ActivationError::WithPartialResult {
                        result: state.clone(),
                        source: e.into(),
                    }
                })?;
                // Check whether this file is a backup or plain link in the old state.
                if old_state.files.contains(&target) {
                    state.files.insert(target);
                } else {
                    state.backed_up_files.insert(target);
                }
            } else if file.replace_existing || target_is_in_systemd_dir {
                log::debug!(
                    "{} already exists but it's set to replace. Backup and link again.",
                    file.source
                );
                state = backup_and_link(&target, &file.source.store_path, state)?;
            } else {
                return Err(ActivationError::with_partial_result(
                    state,
                    anyhow::anyhow!(
                        "Unmanaged path already exists in filesystem, please remove it or use replaceExisting and run system-manager again: {}.",
                        target.display()
                    ),
                ));
            }
        } else {
            // Target do not exist on the filesystem
            log::debug!("Symlink {} => {}", file.source, target.display());
            unix::fs::symlink(file.source.store_path, &target).map_err(|e| {
                ActivationError::WithPartialResult {
                    result: state.clone(),
                    source: e.into(),
                }
            })?;
            state.files.insert(target);
        }
    } else {
        log::debug!("{} is a regular file", file.source);
        state = copy_file(&file.source.store_path, &target, &file, old_state, state)?;
    }
    Ok(state)
}

fn backup_and_link(
    target: &Path,
    link_path: &Path,
    mut dir_state: EtcFilesState,
) -> EtcActivationResult {
    backup_existing_file(target)
        .map_err(|e| ActivationError::with_partial_result(dir_state.clone(), e))?;
    log::debug!("Symlink {} => {}", link_path.display(), target.display());
    unix::fs::symlink(link_path, target).map_err(|e| ActivationError::WithPartialResult {
        result: dir_state.clone(),
        source: e.into(),
    })?;
    dir_state.backed_up_files.insert(target.to_owned());
    Ok(dir_state)
}

/// Check whether link_path is inside a systemd .wants or .requires directory.
fn is_inside_systemd_dependency_dir(link_path: &Path) -> bool {
    link_path
        .parent()
        .map(|parent| {
            parent
                .extension()
                .filter(|ext| ["wants", "requires"].iter().any(|other| other == ext))
                .is_some()
                && parent
                    .parent()
                    .map(|pp| pp.ends_with("systemd/system"))
                    .unwrap_or(false)
        })
        .unwrap_or(false)
}

fn find_uid(entry: &EtcFile) -> anyhow::Result<u32> {
    if !get_uid_gid_regex().is_match(&entry.user) {
        nix::unistd::User::from_name(&entry.user)
            .map(|maybe_user| {
                maybe_user.map_or_else(
                    || {
                        log::warn!(
                            "Specified user {} not found, defaulting to root",
                            &entry.user
                        );
                        0
                    },
                    |user| user.uid.as_raw(),
                )
            })
            .map_err(|err| anyhow::anyhow!(err).context("Failed to determine user"))
    } else {
        Ok(entry.uid)
    }
}

fn find_gid(entry: &EtcFile) -> anyhow::Result<u32> {
    if !get_uid_gid_regex().is_match(&entry.group) {
        nix::unistd::Group::from_name(&entry.group)
            .map(|maybe_group| {
                maybe_group.map_or_else(
                    || {
                        log::warn!(
                            "Specified group {} not found, defaulting to root",
                            &entry.group
                        );
                        0
                    },
                    |group| group.gid.as_raw(),
                )
            })
            .map_err(|err| anyhow::anyhow!(err).context("Failed to determine group"))
    } else {
        Ok(entry.gid)
    }
}

/// Copy a file from source to target.
/// Failing to copy a file shouldn't stop the overall activation, hence the anyhow return.
fn copy_file(
    source: &Path,
    target: &PathBuf,
    entry: &EtcFile,
    old_state: &EtcFilesState,
    mut new_state: EtcFilesState,
) -> EtcActivationResult {
    let exists = target.exists() || target.is_symlink();
    let exists_and_need_backup = exists && !old_state.contains(target) && entry.replace_existing;
    if exists && !old_state.contains(target) {
        if exists_and_need_backup {
            backup_existing_file(target).map_err(|e| ActivationError::WithPartialResult {
                result: new_state.clone(),
                source: e,
            })?;
        } else {
            let error = anyhow!("File {} already exists, ignoring. Set replaceExisting if you want to back it up and override it.", target.display());
            return Err(ActivationError::WithPartialResult {
                result: new_state,
                source: error,
            });
        }
    };
    log::debug!(
        "Copying file {} to {}...",
        source.display(),
        target.display()
    );
    fn to_activation_result<E: Into<anyhow::Error>>(
        e: E,
        state: &EtcFilesState,
    ) -> ActivationError<EtcFilesState> {
        ActivationError::WithPartialResult {
            result: state.clone(),
            source: e.into(),
        }
    }
    if exists && old_state.contains(target) {
        log::debug!("remove {}, we're managing it.", target.display());
        fs::remove_file(target).map_err(|e| to_activation_result(e, &new_state))?;
    }
    log::debug!("copy {} to {}", source.display(), target.display());
    fs::copy(source, target).map_err(|e| to_activation_result(e, &new_state))?;
    let mode_int =
        u32::from_str_radix(&entry.mode, 8).map_err(|e| to_activation_result(e, &new_state))?;
    fs::set_permissions(target, Permissions::from_mode(mode_int))
        .map_err(|e| to_activation_result(e, &new_state))?;
    unixfs::chown(
        target,
        Some(find_uid(entry).map_err(|e| to_activation_result(e, &new_state))?),
        Some(find_gid(entry).map_err(|e| to_activation_result(e, &new_state))?),
    )
    .map_err(|e| to_activation_result(e, &new_state))?;
    // Update the state depending whether or not we backed up a file before
    if exists_and_need_backup || (old_state.backed_up_files.contains(target)) {
        new_state.backed_up_files.insert(target.clone());
    } else {
        new_state.files.insert(target.clone());
    }
    Ok(new_state)
}
