name: update-nix-version
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1" # runs weekly every Monday at 04:00 UTC

jobs:
  bump-nix:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repo"
        uses: "actions/checkout@v6"
      - name: "Install the Nix package manager"
        uses: "cachix/install-nix-action@master"
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Bump Nix version in nix-artifacts"
        run: python3 tools/bump_nix_version.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Create Pull Request"
        uses: "peter-evans/create-pull-request@v8"
        with:
          branch: "auto_update_nix_version"
          title: "Bump Nix version in nix-artifacts"
          body: |
            Automatically bumped the Nix version and hashes in nix-artifacts.
          commit-message: "bump nix version in nix-artifacts"
